version: "3.7"
services:
  app:
    build:
      args:
        user: fanpero
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: amis-minners
    container_name: amis-minners-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - minners

  db:
    image: mysql:5.7.33
    container_name: amis-minners-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - minners

  nginx:
    image: nginx:alpine
    container_name: amis-minners-nginx
    restart: unless-stopped
    ports:
      - 8100:8100
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - minners

networks:
  minners:
    driver: bridge
