version: "3.7"
services:
  #Laravel Application
  app:
    build:
      args:
        user: minner
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: amis-minners
    container_name: amis-minners-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - amis-minners_default

  # Database Service
  db:
    image: mariadb:10.5.6
    container_name: amis-minners-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_minner
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/database.sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - amis-minners_default

  # Webserver Service
  nginx:
    image: nginx:latest
    container_name: amis-minners-nginx
    restart: unless-stopped
    ports:
      - 8005:80
    depends_on:
      - db
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - amis-minners_default

networks:
  amis-minners_default:
    driver: bridge

volumes:
  amis-minners_data:
    driver: local
