version: "3.7"
services:
  #Laravel Application
  app:
    build:
      args:
        user: minner
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: amis-minners
    container_name: amis-minners-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./:/var/www
      - ./docker-files/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - amis-minners_default

  # Database Service
  db:
    image: mariadb:10.5.6
    container_name: amis-minners-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_minner
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
      - amis-minners_default

  # Webserver Service
  nginx:
    image: nginx:latest
    container_name: amis-minners-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker-files/nginx:/etc/nginx/conf.d
    networks:
      - amis-minners_default

# Docker Networks
networks:
  amis-minners_default:
    driver: bridge

# Docker Volumes
volumes:
  amis-minners_data:
    driver: local
